### ISSUE TITLE
Create data type for Risk

### ISSUE THREAD

**Issue by dylanratcliffe** [overmindtech/sdp#139]
We will need to be able to attach risks to Changes, this requires a new data type with the following stuff:

* Title
* Severity
* Description (Markdown)
* Related Items

Once this is created it will need to be added to a Change. We should add the risks, but also the status i.e.

* Not yet calculated since we are still defining the change
* Done
* Change too large and risks can't be generated
* Error
* Skipped (plus a reason)

**Comment by dylanratcliffe** [comment]
This pr is also related here: https://github.com/overmindtech/sdp/pull/145

**Comment by dylanratcliffe** [comment]
Update: @DavidS-om & @getinnocuous Will pair on this today

**Comment by getinnocuous** [comment]
@dylanratcliffe would the `relatedItems` field be an array of `ItemDiff` like this 
`repeated ItemDiffSummary relatedItems = 4;`

**Comment by DavidS-om** [comment]
> @dylanratcliffe would the `relatedItems` field be an array of `ItemDiff` like this `repeated ItemDiffSummary relatedItems = 4;`

the `relatedItems` field would be an array of `Reference`
