### ISSUE TITLE
Create GetUsage SDP definitions

### ISSUE THREAD

**Issue by getinnocuous** [overmindtech/sdp#222]
As discussed in [#941](https://github.com/overmindtech/api-server/issues/941), the data returned from Stripe will look similar to below.

```go
type UsageData struct {
	id       string
	cost     float64
	tiers    []*stripe.PriceTier
	quantity int64
}
```

**Comment by getinnocuous** [comment]
Closing this. Upon reflection it makes more sense for the frontend to query Stripe directly rather than adding another step in the chain.

**Comment by dylanratcliffe** [comment]
@getinnocuous Might be worth getting @DavidS-ovm's opinion on where that should live. Even though it's another step, it might be one less place that we have to share the Strip auth stuff for example

**Comment by getinnocuous** [comment]
> @getinnocuous Might be worth getting @DavidS-ovm's opinion on where that should live. Even though it's another step, it might be one less place that we have to share the Strip auth stuff for example

This decision was made as a result of speaking with David. We came to the conclusion that whilst it means another bit of Stripe config/setup, we will be able to move a lot quicker talking to Stripe directly rather than having to go via the api-server.
