### ISSUE TITLE
Move docs-data to source heartbeat API

### ISSUE THREAD

**Issue by dylanratcliffe** [overmindtech/sdp#264]
## Research

* Docs are generated with: https://github.com/overmindtech/docgen
* JSON is move into docs in this workflow: https://github.com/overmindtech/docs.overmind.tech/blob/main/.github/workflows/docgen.yml
* Which then becomes markdown in this javascript: https://github.com/overmindtech/docs.overmind.tech/blob/main/util/generate-docs.js

We still need a way to extract the nice structured data from the code for docs generation, but we also need this to be able to made available to [`discovery`](https://github.com/overmindtech/discovery) and therefore as part of the heartbeats

## Proposed API

@tphoney Can you please fill this one out?

**Comment by tphoney** [comment]
```bash
➜  workspace git:(full_stack_vscode) ✗ grep -ihor "+overmind:\S*" stdlib-source  | sort | uniq
+overmind:description
+overmind:descriptiveType
+overmind:get
+overmind:link
+overmind:linked-item-query
+overmind:search
+overmind:type
➜  workspace git:(full_stack_vscode) ✗ grep -ihor "+overmind:\S*" aws-source  | sort | uniq
+overmind:descriptiveType
+overmind:get
+overmind:group
+overmind:link
+overmind:list
+overmind:search
+overmind:terraform:method
+overmind:terraform:queryMap
+overmind:type
➜  workspace git:(full_stack_vscode) ✗ grep -ihor "+overmind:\S*" k8s-source  | sort | uniq
+overmind:descriptiveType
+overmind:get
+overmind:group
+overmind:link
+overmind:list
+overmind:search
+overmind:terraform:queryMap
+overmind:terraform:scope
+overmind:type
➜  workspace git:(full_stack_vscode) ✗                                
```
gives
+overmind:description
+overmind:descriptiveType
+overmind:get
+overmind:group
+overmind:link
+overmind:linked-item-query
+overmind:list
+overmind:search
+overmind:terraform:method
+overmind:terraform:queryMap
+overmind:terraform:scope
+overmind:type

**Comment by tphoney** [comment]
We could extend the functionality of https://github.com/overmindtech/aws-source/blob/ab5978f87de4d015b4a55758bdae881b507c0967/sources/describe_source.go#L21

adding in the  additional fields that were previously tags.

**Comment by tphoney** [comment]
![Image](https://github.com/user-attachments/assets/8064a875-254f-40ba-bf22-9239cdf72578)

**Comment by tphoney** [comment]
todo 

-  // +overmind:linked-item-query rdap-entity only in stdlib-source/sources/internet/main.go ??te
