### ISSUE TITLE
design Query extension to linkDepth to consider link flavor

### ISSUE THREAD

**Issue by DavidS-om** [overmindtech/sdp#72]
In some situations, it would be convenient to recursively query items while restricting the graph traversal based on attributes of the edge itself. Specifically whether or not the edges are "located in" links or not.

What are the specific capabilities that we really need, and how can we encode that in the Query messages?

**Comment by dylanratcliffe** [comment]
Alternately a `LinkedItemQuery` could be a new type that wrapped a query e.g.

```protobuf
message LinkedItemQuery {
  string LinkType;
  Query Query;
}
```

**Comment by DavidS-om** [comment]
Done as part of #71
